music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/<album-id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/42/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/42/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # /register/
    url(r'^register/$', views.UserFormView.as_view(), name='register')
]

web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^music_json/', include('music_json.urls')),
    url(r'^customer_support/', include('customer_support.urls')),
    url(r'^payment_system/', include('payment_system.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

music/models.py
from __future__ import print_function
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from web.utilities import get_media_path
from sorl.thumbnail import get_thumbnail

import datetime


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.ImageField(upload_to=get_media_path, max_length=255)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + " : " + self.artist

    def get_songs(self):
        return self.song_set.all()

    def get_different_sized_logo(self):
        """
        Generates different sized logos of the album
        :return: json containing the different sized images
        """
        # print('get_different_sized_logo')
        sizes = [50, 100, 150]
        sized_logos = {}
        for size in sizes:
            # print(size)
            sized_logo = get_thumbnail(self.album_logo, str(size), quality=99)
            # print(sized_logo.url)
            sized_logos['logo_' + str(size)] = sized_logo.url
        # print(sized_logos)
        return sized_logos

    def to_json(self):
        json = {'id': self.id, 'artist': self.artist, 'title': self.album_title,
                'genre': self.genre, 'logo': self.album_logo.url}
        songs = []
        for song in self.get_songs():
            songs.append(song.to_json())
        json['songs'] = songs
        # Getting different sized logos
        print('getting logos')
        print(datetime.datetime.now().time())
        json.update(self.get_different_sized_logo())
        print(datetime.datetime.now().time())
        print('done getting logos')
        return json


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

    def to_json(self):
        json = {'id': self.id, 'title': self.song_title}
        return json

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View

from models import Album
from forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # Display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # Cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # Returns user object if credentials are correct
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block title %}Add a new Album {% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Add a new Album</h3>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>

    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block albums_active %}{% endblock %}">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                        </a>
                    </li>
{#                    <li class="active">#}
{#                        <a href="{% url 'music:index' %}">#}
{#                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums#}
{#                        </a>#}
{#                    </li>#}

{#                    <li class="{% block songs_active %}{% endblock %}">#}
{#                        <a href="{% url 'music:songs' 'all' %}">#}
{#                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs#}
{#                        </a>#}
{#                    </li>#}
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
{#    <img src='{{ album.album_logo.url }}' style="width: 250px;">#}
{##}
{#    <h1>{{ album.album_title }}</h1>#}
{#    <h2>{{ album.artist }}</h2>#}
{##}
{#    {% for song in album.song_set.all %}#}
{#        {{ song.song_title }}#}
{#        {% if song.is_favourite %}#}
{#            <img src="http://images.clipartpanda.com/yellow-stars-images-yellow_star_coloring_book_colouring.png"#}
{#            width="16" height="16">#}
{#        {% endif %}#}
{#        <br/>#}
{#    {% endfor %}#}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
{#                <li role="presentation"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>#}
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
{#                                    <a target="_blank" href="{{ song.audio_file.url }}">#}
                                    <a target="_blank" href="#">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
{#                                    <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>#}
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
{#                                    <form action="{% url 'music:delete_song' album.id song.id %}" method="post" style="display: inline;">#}
                                    <form action="#" method="get" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block albums_active %}active{% endblock %}

{% block body %}
{#    <ul>#}
{#        {% for album in all_albums %}#}
{#            <li><a href="{% url 'music:detail' album.id %}">    {{ album.album_title }}</a></li>#}
{#        {% endfor %}#}
{#    </ul>#}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
{#                            <a href="{% url 'music:favorite_album' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">#}
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

{#    <!-- If user searches and there are songs -->#}
{#    {% if songs %}#}
{#        <div class="row">#}
{#            <div class="col-sm-12">#}
{#                <h3>Songs</h3>#}
{#            </div>#}
{#            <div class="col-sm-12">#}
{#                <div class="panel panel-default">#}
{#                    <div class="panel-body">#}
{#                        <table class="table">#}
{#                            <thead>#}
{#                                <tr>#}
{#                                    <th>Song Title</th>#}
{#                                    <th>Artist</th>#}
{#                                    <th>Audio File</th>#}
{#                                    <th>Album</th>#}
{#                                    <th>Favorite</th>#}
{#                                </tr>#}
{#                            </thead>#}
{#                            <tbody>#}
{#                                {% for song in songs %}#}
{#                                    <tr>#}
{#                                        <td>{{ song.song_title }}</td>#}
{#                                        <td>{{ song.album.artist }}</td>#}
{#                                        <td>#}
{#                                            <a target="_blank" href="{{ song.audio_file.url }}">#}
{#                                                <button type="button" class="btn btn-success btn-xs">#}
{#                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play#}
{#                                                </button>#}
{#                                            </a>#}
{#                                        </td>#}
{#                                        <td>#}
{#                                            <a href="{% url 'music:detail' song.album.id %}">#}
{#                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />#}
{#                                            </a>#}
{#                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>#}
{#                                        </td>#}
{#                                        <td>#}
{#                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>#}
{#                                        </td>#}
{#                                    </tr>#}
{#                                {% endfor %}#}
{#                            </tbody>#}
{#                        </table>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}

</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}

{% block title %}Register{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a new account</h3>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}